name: gedixr_env
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - geopandas>=1.0.0
  - h5py
  - tqdm
  - geocube
  - pyarrow
  - typer
  - harmony-py
  - earthaccess
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python
